# Generated by Django 4.2 on 2025-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='temp_field',
            field=models.CharField(default='teste', max_length=50),
        ),
    ]
