# Generated by Django 4.2 on 2025-07-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='temp_field',
        ),
    ]
