# Generated by Django 4.2 on 2025-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada')], default='Pendente', max_length=20),
        ),
    ]
